spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dhmusicstreamingsong@gmail.com
    password: bvhpkyqtlvlmqsrm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
